Config = Config or {}

Config.UsingPsHousing = false
Config.UsingDefaultQBApartments = false
Config.OnlyShowOnDuty = true
Config.UseCQCMugshot = true

-- Front, Back Side. Use 4 for both sides, we recommend leaving at 1 for default.
Config.MugPhotos = 1

-- If set to true = Fine gets automatically removed from bank automatically charging the player.
-- If set to false = The fine gets sent as an Invoice to their phone and it us to the player to pay for it, can remain unpaid and ignored.
Config.BillVariation = true

-- If set to false (default) = The fine amount is just being removed from the player's bank account
-- If set to true = The fine amount is beeing added to the society account after being removed from the player's bank account
Config.QBManagementUse = true

-- Set up your inventory to automatically retrieve images when a weapon is registered at a weapon shop or self-registered.
-- If you're utilizing lj-inventory's latest version from GitHub, no further modifications are necessary. 
-- However, if you're using a different inventory system, please refer to the "Inventory Edit | Automatic Add Weapons with images" section in ps-mdt's README.
Config.InventoryForWeaponsImages = "ox_inventory"

-- "LegacyFuel", "lj-fuel", "ps-fuel"
Config.Fuel = "ox_fuel"

-- Google Docs Link
Config.sopLink = {
    ['police'] = 'https://docs.google.com/spreadsheets/d/1lYywbIA25-6CDXvoXW9Zj6MvOxOtUYcWZF1LNgQeAOA/edit',
    ['ambulance'] = 'https://docs.google.com/document/d/16Oq7j_LmvpqXvGm0dkvRCwATmsj1d8K7nG9QUVIxUXI/edit',
    ['bcso'] = 'https://docs.google.com/document/d/16Oq7j_LmvpqXvGm0dkvRCwATmsj1d8K7nG9QUVIxUXI/edit',
    ['doj'] = 'https://docs.google.com/document/d/16Oq7j_LmvpqXvGm0dkvRCwATmsj1d8K7nG9QUVIxUXI/edit',
    ['sast'] = 'https://docs.google.com/document/d/16Oq7j_LmvpqXvGm0dkvRCwATmsj1d8K7nG9QUVIxUXI/edit',
    ['sasp'] = 'https://docs.google.com/document/d/16Oq7j_LmvpqXvGm0dkvRCwATmsj1d8K7nG9QUVIxUXI/edit',
    ['doc'] = 'https://docs.google.com/document/d/16Oq7j_LmvpqXvGm0dkvRCwATmsj1d8K7nG9QUVIxUXI/edit',
    ['lssd'] = 'https://docs.google.com/document/d/16Oq7j_LmvpqXvGm0dkvRCwATmsj1d8K7nG9QUVIxUXI/edit',
    ['sapr'] = 'https://docs.google.com/document/d/16Oq7j_LmvpqXvGm0dkvRCwATmsj1d8K7nG9QUVIxUXI/edit',
}

-- Google Docs Link
Config.RosterLink = {
    ['police'] = 'https://docs.google.com/spreadsheets/d/1VA0XN91Silz0546dSKvUIx4EuT1cPlSyF1nvGduRbWs/edit',
    ['ambulance'] = 'https://docs.google.com/spreadsheets/d/1VA0XN91Silz0546dSKvUIx4EuT1cPlSyF1nvGduRbWs/edit',
    ['bcso'] = 'https://docs.google.com/spreadsheets/d/1VA0XN91Silz0546dSKvUIx4EuT1cPlSyF1nvGduRbWs/edit',
    ['doj'] = 'https://docs.google.com/spreadsheets/d/1VA0XN91Silz0546dSKvUIx4EuT1cPlSyF1nvGduRbWs/edit',
    ['sast'] = 'https://docs.google.com/spreadsheets/d/1VA0XN91Silz0546dSKvUIx4EuT1cPlSyF1nvGduRbWs/edit',
    ['sasp'] = 'https://docs.google.com/spreadsheets/d/1VA0XN91Silz0546dSKvUIx4EuT1cPlSyF1nvGduRbWs/edit',
    ['doc'] = 'https://docs.google.com/spreadsheets/d/1VA0XN91Silz0546dSKvUIx4EuT1cPlSyF1nvGduRbWs/edit',
    ['lssd'] = 'https://docs.google.com/spreadsheets/d/1VA0XN91Silz0546dSKvUIx4EuT1cPlSyF1nvGduRbWs/edit',
    ['sapr'] = 'https://docs.google.com/spreadsheets/d/1VA0XN91Silz0546dSKvUIx4EuT1cPlSyF1nvGduRbWs/edit',	
}

Config.PoliceJobs = {
    ['police'] = true,
    --['lspd'] = true,
    --['bcso'] = true,
    ['sast'] = true,
    --['sasp'] = true,
    ['doc'] = true -- no comma .
    --['lssd'] = true,
    --['sapr'] = true,
    --['pa'] = true
}

Config.AmbulanceJobs = {
    ['ambulance'] = true
    --['doctor'] = true
}

Config.DojJobs = {
    ['lawyer'] = true,
    --['lawyer2'] = true,
    ['procureur'] = true,
    ['judge'] = true
}

-- This is a workaround solution because the qb-menu present in qb-policejob fills in an impound location and sends it to the event. 
-- If the impound locations are modified in qb-policejob, the changes must also be implemented here to ensure consistency.

Config.ImpoundLocations = {
    [1] = vector4(436.68, -1007.42, 27.32, 180.0),
    [2] = vector4(-436.14, 5982.63, 31.34, 136.0),
}

-- Support for Wraith ARS 2X. 

Config.UseWolfknightRadar = true
Config.WolfknightNotifyTime = 5000 -- How long the notification displays for in milliseconds (30000 = 30 seconds)
Config.PlateScanForDriversLicense = true -- If true, plate scanner will check if the owner of the scanned vehicle has a drivers license

-- IMPORTANT: To avoid making excessive database queries, modify this config to true 'CONFIG.use_sonorancad = true' setting in the configuration file located at 'wk_wars2x/config.lua'. 
-- Enabling this setting will limit plate checks to only those vehicles that have been used by a player.

Config.LogPerms = {
	['ambulance'] = {
		[5] = true,
		[6] = true,
	},
	['police'] = {
		[5] = true,
		[6] = true,
	},
    ['bcso'] = {
		[5] = true,
		[6] = true,
	},
    ['sast'] = {
		[5] = true,
		[6] = true,
	},
    ['sasp'] = {
		[5] = true,
		[6] = true,
	},
    ['sapr'] = {
		[5] = true,
		[6] = true,
	},
    ['doc'] = {
		[5] = true,
		[6] = true,
	},
    ['lssd'] = {
		[5] = true,
		[6] = true,
	},
}

Config.RemoveIncidentPerms = {
	['ambulance'] = {
		[5] = true,
		[6] = true,
	},
	['police'] = {
		[5] = true,
		[6] = true,
	},
    ['bcso'] = {
		[5] = true,
		[6] = true,
	},
    ['sast'] = {
		[5] = true,
		[6] = true,
	},
    ['sasp'] = {
		[5] = true,
		[6] = true,
	},
    ['sapr'] = {
		[5] = true,
		[6] = true,
	},
    ['doc'] = {
		[5] = true,
		[6] = true,
	},
    ['lssd'] = {
		[5] = true,
		[6] = true,
	},
}

Config.RemoveReportPerms = {
	['ambulance'] = {
		[5] = true,
		[6] = true,
	},
	['police'] = {
		[5] = true,
		[6] = true,
	},
    ['bcso'] = {
		[5] = true,
		[6] = true,
	},
    ['sast'] = {
		[5] = true,
		[6] = true,
	},
    ['sasp'] = {
		[5] = true,
		[6] = true,
	},
    ['sapr'] = {
		[5] = true,
		[6] = true,
	},
    ['doc'] = {
		[5] = true,
		[6] = true,
	},
    ['lssd'] = {
		[5] = true,
		[6] = true,
	},
}

Config.RemoveWeaponsPerms = {
	['ambulance'] = {
		[5] = true,
		[6] = true,
	},
	['police'] = {
		[5] = true,
		[6] = true,
	},
    ['bcso'] = {
		[5] = true,
		[6] = true,
	},
    ['sast'] = {
		[5] = true,
		[6] = true,
	},
    ['sasp'] = {
		[5] = true,
		[6] = true,
	},
    ['sapr'] = {
		[5] = true,
		[6] = true,
	},
    ['doc'] = {
		[5] = true,
		[6] = true,
	},
    ['lssd'] = {
		[5] = true,
		[6] = true,
	},
}

Config.PenalCodeTitles = {
    [1] = 'CRIMES ENVERS LA PERSONNE',
    [2] = 'CRIMES RELATIFS AU VOL',
    [3] = 'CRIMES RELATIFS À LA FRAUDE',
    [4] = 'CRIMES ENVERS LA PROPRIÉTÉ',
    [5] = 'CRIMES ENVERS L\'ADMINISTRATION PUBLIQUE',
    [6] = 'CRIMES ENVERS L\'ORDRE PUBLIC',
    [7] = 'CRIMES RELATIFS À LA SANTÉ ET AUX MOEURS',
    [8] = 'CRIMES ENVERS LA SÉCURITÉ PUBLIQUE',
    [9] = 'CRIMES RELATIFS À LA CONDUITE D\'UN VÉHICULE',
    [10] = 'CRIMES ENVERS LA FAUNE',
}

Config.PenalCode = {
    [1] = {
        [1] = {title = 'Agression 3ème degré', class = 'Délit', id = 'P.C. 1001', months = 15, fine = 650, color = 'green', description = 'Voies de fait intentionnelles (sans arme)'},
        [2] = {title = 'Agression 2ème degré', class = 'Délit', id = 'P.C. 1002', months = 15, fine = 650, color = 'orange', description = 'Blessures intentionnelles (sans arme)'},
        [3] = {title = 'Agression 1er degré', class = 'Crime', id = 'P.C. 1003', months = 10, fine = 350, color = 'orange', description = 'Blessures corporelles involontaires résultant d\'une confrontation avec circonstances aggravantes (sans arme)'},
        [4] = {title = 'Agression armée', class = 'Crime', id = 'P.C. 1004', months = 20, fine = 350, color = 'red', description = 'Blessures corporelles intentionnelles, blessures corporelles causées sciemment ou blessures corporelles causées par imprudence, entraînant des blessures corporelles graves ou l\'utilisation ou l\'exhibition d\'une arme mortelle'},
        [5] = {title = 'Homicide involontaire', class = 'Crime', id = 'P.C. 1005', months = 30, fine = 1000, color = 'red', description = 'Homicide involontaire par imprudence'},
        [6] = {title = 'Homicide véhiculaire involontaire', class = 'Crime', id = 'P.C. 1006', months = 30, fine = 1000, color = 'red', description = 'Homicide véhiculaire involontaire par imprudence'},
    --    [7] = {title = 'Tentative de meurtre sur civil', class = 'Crime', id = 'P.C. 1007', months = 60, fine = 2000, color = 'red', description = 'Homicide volontaire sur un civil'},
        [7] = {title = 'Meurtre 2ème degré', class = 'Crime', id = 'P.C. 1008', months = 200, fine = 10000, color = 'red', description = 'Meurtre non-prémédité (action avec intention de causer des blessures graves ayant causé la mort)'},
        [8] = {title = 'Complice ou accessoire de meurtre 2ème degré', class = 'Crime', id = 'P.C. 1009', months = 150, fine = 5000, color = 'red', description = 'Avoir été présent délibérément et/ou avoir participé au crime commis'},
        [9] = {title = 'Meurtre 1er degré', class = 'Crime', id = 'P.C. 1010', months = 300, fine = 30000, color = 'red', description = 'Meurtre prémédité.'},
        [10] = {title = 'Complice ou accessoire de meurtre 1er degré', class = 'Crime', id = 'P.C. 1011', months = 200, fine = 15000, color = 'red', description = 'Avoir été présent délibérément et/ou avoir participé au crime commis'},
        [11] = {title = 'Meurtre d\'un agent de la paix ou de la fonction publique', class = 'Crime', id = 'P.C. 1012', months = 500, fine = 50000, color = 'red', description = 'Homicide volontaire sur un agent de la paix ou de la fonction publique'},
        [12] = {title = 'Tentative de meurtre d\'un agent de la paix ou de la fonction publique', class = 'Crime', id = 'P.C. 1013', months = 60, fine = 5000, color = 'red', description = 'Attaque volontaire sur un agent de la paix ou de la fonction publique avec intention de tuer'},
        [13] = {title = 'Complice ou accessoire de meurtre d\'un agent de la paix ou de la fonction publique', class = 'Crime', id = 'P.C. 1014', months = 30, fine = 2500, color = 'red', description = 'Avoir été présent délibérément et/ou avoir participé au crime commis'},
        [14] = {title = 'Détention illégale', class = 'Délit', id = 'P.C. 1015', months = 20, fine = 450, color = 'green', description = 'Retenir une personne contre son gré pour une période prolongée'},
        [15] = {title = 'Enlèvement', class = 'Crime', id = 'P.C. 1016', months = 15, fine = 350, color = 'orange', description = 'Retenir une personne contre son gré pour une courte période'},
        [16] = {title = 'Complice ou accessoire à un enlèvement', class = 'Crime', id = 'P.C. 1017', months = 10, fine = 250, color = 'orange', description = 'Avoir été présent délibérément et/ou avoir participé au crime commis'},
        [17] = {title = 'Tentative d\'enlèvement', class = 'Crime', id = 'P.C. 1018', months = 10, fine = 250, color = 'orange', description = 'L\'action de tenter de retenir une personne contre son gré'},
        [18] = {title = 'Prise d\'otage', class = 'Crime', id = 'P.C. 1019', months = 15, fine = 350, color = 'orange', description = 'Retenir une personne contre son gré dans le but d\'enregistrer des gains'},
        [19] = {title = 'Complice ou accessoire à prise d\'otage', class = 'Crime', id = 'P.C. 1020', months = 15, fine = 275, color = 'orange', description = 'Avoir été présent délibérément et/ou avoir participé au crime commis'},
        [20] = {title = 'Détention illégale d\'un agent de la paix ou de la fonction publique.', class = 'Crime', id = 'P.C. 1021', months = 45, fine = 1000, color = 'orange', description = 'Retenir un agent de la paix ou de la fonction publique contre son gré pour une période prolongée'},
        [21] = {title = 'Menaces criminelles', class = 'Délit', id = 'P.C. 1022', months = 10, fine = 600, color = 'orange', description = 'Menaces articulant l\'intention de commettre un crime envers une personne, une entité légale ou un bien public ou privé'},
        [22] = {title = 'Mise en danger délibérée de la vie d\'autrui.', class = 'Délit', id = 'P.C. 1023', months = 15, fine = 1000, color = 'orange', description = 'Agissements imprudents mettant en danger la vie d\'autrui'},
        [23] = {title = 'Fusillade reliée au crime organisé', class = 'Crime', id = 'P.C. 1024', months = 30, fine = 1000, color = 'red', description = 'Utilisation criminelle d\'une arme dans une situation en lien avec le crime organisé'},
        [24] = {title = 'Cannibalisme', class = 'Crime', id = 'P.C. 1025', months = 1000, fine = 100000, color = 'red', description = 'Volontairement consommer la chair humaine'},
        [25] = {title = 'Torture', class = 'Crime', id = 'P.C. 1026', months = 50, fine = 10000, color = 'red', description = 'Infliger des blessures corporelles dans le but de l\'amusement ou pour soutirer des informations'},
    },
    [2] = {
        [1] = {title = 'Vol mineur', class = 'Infraction', id = 'P.C. 2001', months = 10, fine = 250, color = 'green', description = 'Vol de biens dont la valeur est inférieure à 500$'},
        [2] = {title = 'Vol avec circonstances aggravantes', class = 'Délit', id = 'P.C. 2002', months = 20, fine = 300, color = 'green', description = 'Vol de biens dont la valeur est supérieure à 500$ et inférieure à 999$'},
        [3] = {title = 'Vol de voiture', class = 'Crime', id = 'P.C. 2003', months = 15, fine = 600, color = 'green', description = 'Voler un véhicule stationné de façon non-violente'},
        [4] = {title = 'Vol de voiture armé', class = 'Crime', id = 'P.C. 2004', months = 25, fine = 750, color = 'green', description = 'Voler un véhicule stationné à l\aide d\'une arme'},
        [5] = {title = 'Vol de voiture avec agression armée', class = 'Crime', id = 'P.C. 2005', months = 30, fine = 1000, color = 'orange', description = 'Forcer à l\'aide d\'une arme les occupants d\'un véhicule afin d\'en prendre possession'},
        [6] = {title = 'Cambriolage', class = 'Délit', id = 'P.C. 2006', months = 15, fine = 500, color = 'green', description = 'Entrée par effraction dans un bâtiment dans le but d\'y voler des biens'},
        [7] = {title = 'Vol avec violence', class = 'Crime', id = 'P.C. 2007', months = 30, fine = 1000, color = 'green', description = 'Prendre possession illégalement de biens d\'autrui par l\'usage de la force ou la menace de la force'},
        [8] = {title = 'Complice ou accesoire de vol à main armée', class = 'Crime', id = 'P.C. 2008', months = 10, fine = 1000, color = 'green', description = 'Avoir été présent délibérément et/ou avoir participé au crime commis'},
        [9] = {title = 'Tentative de vol avec violence', class = 'Crime', id = 'P.C. 2009', months = 10, fine = 1000, color = 'green', description = 'Tenter de prendre possession illégalement de biens d\'autrui par l\'usage de la force ou la menace de la force'},
        [10] = {title = 'Vol à main armée', class = 'Crime', id = 'P.C. 2010', months = 15, fine = 800, color = 'orange', description = 'Prendre, à main armée, possession illégalement de biens d\'autrui par l\'usage de la force ou la menace de la force'},
        [11] = {title = 'Complice ou accessoire de vol à main armée', class = 'Crime', id = 'P.C. 2011', months = 10, fine = 600, color = 'orange', description = 'Avoir été présent délibérément et/ou avoir participé au crime commis'},
        [12] = {title = 'Tentative de vol à main armée', class = 'Crime', id = 'P.C. 2012', months = 10, fine = 500, color = 'orange', description = 'Tenter, à main armée, de prendre possession illégalement de biens d\'autrui par l\'usage de la force ou la menace de la force'},
        [13] = {title = 'Vol qualifié', class = 'Crime', id = 'P.C. 2013', months = 25, fine = 750, color = 'orange', description = 'Vol de biens dont la valeur est égale ou supérieure à 1000$'},
        [14] = {title = 'Partir sans payer', class = 'Infraction', id = 'P.C. 2014', months = 5, fine = 250, color = 'green', description = 'Partir d\'un établissement sans avoir payé'},
        [15] = {title = 'Possession de monnaie illégale', class = 'Délit', id = 'P.C. 2015', months = 20, fine = 750, color = 'green', description = 'Avoir en sa possession toute somme d\'argent ayant été obtenue illégalement'},
        [16] = {title = 'Possession illégale d\'objets réservés aux employés gouvernementaux', class = 'Délit', id = 'P.C. 2016', months = 15, fine = 750, color = 'green', description = 'Avoir en sa possession tout objet dont l\'usage et/ou la possession est réservée aux agents de la paix ou de la fonction publique'},
        [17] = {title = 'Possession d\'objets ayant été utilisés pour commettre un crime', class = 'Délit', id = 'P.C. 2017', months = 15, fine = 400, color = 'green', description = 'Avoir en sa possession tout objet pouvant être lié à un crime commis'},
        [18] = {title = 'Vente d\'objets ayant été utilisés pour commettre un crime', class = 'Crime', id = 'P.C. 2018', months = 5, fine = 750, color = 'orange', description = 'Faire la revente de tout objet pouvant être lié à un crime commis'},
        [19] = {title = 'Vol d\'un aéronef', class = 'Crime', id = 'P.C. 2019', months = 25, fine = 1500, color = 'green', description = 'Prendre possession illégalement d\'un aéronef'},
    },
    [3] = {
        [1] = {title = 'Usurpation d\'identité', class = 'Délit', id = 'P.C. 3001', months = 15, fine = 600, color = 'green', description = 'S\'identifier faussement dans l\'optique d\'en tirer un gain quelconque'},
        [2] = {title = 'Usurpation d\'identité d\'un agent de la paix ou de la fonction publique', class = 'Crime', id = 'P.C. 3002', months = 30, fine = 1250, color = 'green', description = 'S\'identifier faussement en tant qu\'agent de la paix ou de la fonction publique dans l\'optique d\'en tirer un gain quelconque'},
        [3] = {title = 'Usurpation d\'identité d\'un juge', class = 'Crime', id = 'P.C. 3003', months = 30, fine = 1250, color = 'green', description = 'S\'identifier faussement en tant que juge dans l\'optique d\'en tirer un gain quelconque'},
        [4] = {title = 'Possession de pièces d\'identité volées', class = 'Délit', id = 'P.C. 3004', months = 10, fine = 350, color = 'green', description = 'Avoir en sa possession les preuves d\'identité d\'une autre personne sans son consentement'},
        [5] = {title = 'Possession de pièces d\'identité volées d\'un agent de la paix ou de la fonction publique ', class = 'Délit', id = 'P.C. 3005', months = 15, fine = 750, color = 'green', description = 'Avoir en sa possession les preuves d\'identité d\'un agent de la paix ou de la fonction publique sans son consentement'},
        [6] = {title = 'Extorsion', class = 'Crime', id = 'P.C. 3006', months = 20, fine = 1000, color = 'orange', description = 'Menacer et/ou causer des blessures à autrui dans le but d\'en tirer un gain financier'},
        [7] = {title = 'Fraude', class = 'Délit', id = 'P.C. 3007', months = 25, fine = 3000, color = 'green', description = 'Commettre un abus de confiance dans le but d\'en tirer un gain financier'},
        [8] = {title = 'Contrefaçon', class = 'Délit', id = 'P.C. 3008', months = 20, fine = 1000, color = 'green', description = 'Falsifier un document notarié ou officiel dans le but d\'en tirer un gain financier'},
        [9] = {title = 'Blanchiment d\'argent', class = 'Crime', id = 'P.C. 3009', months = 25, fine = 2000, color = 'red', description = 'Opération visant à légitimiser toute somme d\'argent obtenue illégalement'},
    },
    [4] = {
        [1] = {title = 'Violation de propriété', class = 'Délit', id = 'P.C. 4001', months = 10, fine = 300, color = 'green', description = 'Lorsqu\'une personne se trouve à l\'intérieur des délimitations d\'une propriété illégalement et/ou sans y être autorisé'},
        [2] = {title = 'Violation de propriété criminelle', class = 'Crime', id = 'P.C. 4002', months = 15, fine = 500, color = 'green', description = 'Lorsqu\'une personne se trouve à l\'intérieur des délimitations d\'une propriété illégalement et/ou sans y être autorisé à répétition'},
        [3] = {title = 'Incendie criminel', class = 'Crime', id = 'P.C. 4003', months = 30, fine = 1500, color = 'orange', description = 'Utilisation du feu ou d\'accélérants pour endommager, détruire, blesser ou tuer une personne ou une propriété'},
        [4] = {title = 'Vandalisme', class = 'Infraction', id = 'P.C. 4004', months = 15, fine = 500, color = 'green', description = 'Endommager ou détruire/tenter de détruire une propriété ou des biens'},
        [5] = {title = 'Vandalisme d\'une propriété gouvernementale', class = 'Crime', id = 'P.C. 4005', months = 25, fine = 1500, color = 'green', description = 'Endommager ou détruire/tenter de détruire une propriété ou des biens gouvernementaux'},
        [6] = {title = 'Jet d\'ordures', class = 'Infraction', id = 'P.C. 4006', months = 0, fine = 100, color = 'green', description = 'Jeter des items à des endroits inappropriés'},
    },
    [5] = {
        [1] = {title = 'Corruption d\'un fonctionnaire gouvernemental', class = 'Crime', id = 'P.C. 5001', months = 30, fine = 1000, color = 'green', description = 'Utilisation de sommes d\'argent, de faveurs ou de biens afin d\'obtenir des services de la part d\'un agent de la paix ou de la sécurité publique'},
        [2] = {title = 'Port du masque en public', class = 'Infraction', id = 'P.C. 5002', months = 0, fine = 150, color = 'green', description = 'Action de porter un masque dans tout lieu public, incluant les commerces et autres établissements privés ayant un accès public'},
        [3] = {title = 'Possession de contrebande dans un édifice gouvernemental', class = 'Crime', id = 'P.C. 5003', months = 15, fine = 750, color = 'green', description = 'Possession de tout item illégal à l\'intérieur d\'un bâtiment gouvernemental'},
        [4] = {title = 'Possession criminelle de biens volés', class = 'Délit', id = 'P.C. 5004', months = 10, fine = 300, color = 'green', description = 'Possession, volontaire ou non, d\'objets ayant été obtenus illégalement'},
        [5] = {title = 'Évasion', class = 'Crime', id = 'P.C. 5005', months = 30, fine = 1500, color = 'green', description = 'S\'échapper délibérément ou non à une détention lorsqu\'en état d\'arrestation, de détention provisoire et/ou à l\'intérieur d\'un établissement de détention ou de tout bâtiment dans lequel la personne est sous détention légale'},
        [6] = {title = 'Évasion de prison', class = 'Crime', id = 'P.C. 5006', months = 45, fine = 2500, color = 'orange', description = 'S\'échapper délibérément ou non d\'un établissement correctionnel fédéral'},
        [7] = {title = 'Complice ou accessoire à évasion de prison', class = 'Crime', id = 'P.C. 5007', months = 25, fine = 750, color = 'orange', description = 'Avoir été présent délibérément et/ou avoir participé au crime commis'},
        [8] = {title = 'Tentative d\'évasion de prison', class = 'Crime', id = 'P.C. 5008', months = 25, fine = 750, color = 'orange', description = 'Tenter de s\'échapper délibérément ou non d\'un établissement correctionnel fédéral'},
        [9] = {title = 'Parjure', class = 'Crime', id = 'P.C. 5009', months = 200, fine = 15000, color = 'green', description = 'Mentir ou omettre la vérité lorsque sous serment'},
        [10] = {title = 'Non-respect d\'une ordonnance de restriction', class = 'Crime', id = 'P.C. 5010', months = 30, fine = 3000, color = 'green', description = 'Violation délibérée d\'une ordonnance de protection de la cour'},
        [11] = {title = 'Abus de confiance', class = 'Crime', id = 'P.C. 5011', months = 60, fine = 5000, color = 'green', description = 'Détournement délibéré de fonds provenant de comptes non-personnels vers un ou plusieurs comptes personnels dans le but d\'en tirer un gain financier'},
        [12] = {title = 'Pratique illégale', class = 'Crime', id = 'P.C. 5012', months = 30, fine = 1000, color = 'orange', description = 'Fournir un ou des services sans les autorisations légales nécéssaires'},
        [13] = {title = 'Mauvais usage des systèmes d\'urgence', class = 'Infraction', id = 'P.C. 5013', months = 0, fine = 500, color = 'orange', description = 'Utiliser malicieusement et/ou à des fins ludiques et/ou non-urgentes tout système gouvernemental de traitement des urgences'},
        [14] = {title = 'Conspiration', class = 'Délit', id = 'P.C. 5014', months = 20, fine = 400, color = 'green', description = 'Planifier un crime sans toutefois le commettre'},
        [15] = {title = 'Non-respect d\'un ordre de la cour', class = 'Délit', id = 'P.C. 5015', months = 50, fine = 10000, color = 'orange', description = 'Violation délibérée d\'un ordre de la cour'},
        [16] = {title = 'Défaut de comparution', class = 'Délit', id = 'P.C. 5016', months = 50, fine = 10000, color = 'orange', description = 'Ne pas se présenter en cour lorsque mandaté'},
        [17] = {title = 'Outrage à la cour', class = 'Crime', id = 'P.C. 5017', months = 30, fine = 2000, color = 'orange', description = 'Déranger volontaire les procédures légales en cours à la cour de justice'},
        [18] = {title = 'Résistance à arrestation', class = 'Délit', id = 'P.C. 5018', months = 20, fine = 400, color = 'orange', description = 'Refuser de coopération lors d\'une mise en détention d\'un agent de la paix'},
        [19] = {title = 'Bris de condition', class = 'Crime', id = 'P.C. 5019', months = 50, fine = 5000, color = 'orange', description = 'Violation, délibérée ou non, d\'une peine de probation.'},
    },
    [6] = {
        [1] = {title = 'Refus d\'obtempérer', class = 'infraction', id = 'P.C. 6001', months = 10, fine = 500, color = 'green', description = 'Délibérément refuser de respecter un ordre d\'un agent de la paix'},
        [2] = {title = 'Trouble à l\'ordre public', class = 'Infraction', id = 'P.C. 6002', months = 5, fine = 250, color = 'green', description = 'Agir de manière à créer une condition dangereuse ou physiquement offensante par un acte qui ne sert aucun but légitime de l\'auteur'},
        [3] = {title = 'Trouble à la tranquillité publique', class = 'infraction', id = 'P.C. 6003', months = 5, fine = 250, color = 'green', description = 'Agir de manière à provoquer des troubles et perturber l\'ordre public'},
        [4] = {title = 'Déclaration mensongère', class = 'Délit', id = 'P.C. 6004', months = 10, fine = 750, color = 'green', description = 'Reporter un crime n\'ayant pas été commis'},
        [5] = {title = 'Harcèlement', class = 'Délit', id = 'P.C. 6005', months = 25, fine = 400, color = 'orange', description = 'Assaults verbaux et/ou menacants à répétition envers autrui'},
        [6] = {title = 'Entrave à la justice', class = 'Délit', id = 'P.C. 6006', months = 15, fine = 750, color = 'green', description = 'Agir de manière à entraver le processus de la justice ou les enquêtes légales'},
        [7] = {title = 'Entrave criminelle à la justice', class = 'Crime', id = 'P.C. 6007', months = 25, fine = 900, color = 'green', description = 'Agir de manière à entraver le processus de la justice ou les enquêtes légales de manière violente'},
        [8] = {title = 'Incitation à l\'émeute', class = 'Crime', id = 'P.C. 6008', months = 0, fine = 250, color = 'orange', description = 'Provoquer des troubles civils de manière à inciter un groupe à causer des préjudices aux personnes ou aux biens'},
        [9] = {title = 'Flânage à un édifice de la fonction publique', class = 'Infraction', id = 'P.C. 6009', months = 0, fine = 150, color = 'green', description = 'Présence prolongée sur une propriété gouvernementale'},
        [10] = {title = 'Tentative de manipulation', class = 'Délit', id = 'P.C. 6010', months = 10, fine = 500, color = 'green', description = 'Interférence volontaire, délibérée et indirecte avec des points clés d\'une enquête légale'},
        [11] = {title = 'Tentative de manipulation de voiture', class = 'Délit', id = 'P.C. 6011', months = 15, fine = 500, color = 'green', description = 'Interférence délibérée et intentionnelle avec le fonctionnement normal d\'un véhicule'},
        [12] = {title = 'Tentative de manipulation d\'évidence', class = 'Crime', id = 'P.C. 6012', months = 20, fine = 500, color = 'green', description = 'Interférence délibérée et intentionnelle avec des éléments de preuve issus d\'une enquête légale'},
        [13] = {title = 'Tentative de manipulation de témoin', class = 'Crime', id = 'P.C. 6013', months = 25, fine = 1000, color = 'green', description = 'Entraînement volontaire et délibéré ou la contrainte d\'un témoin dans le cadre d\'une enquête légale'},
        [14] = {title = 'Refus de s\'identifier', class = 'Délit', id = 'P.C. 6014', months = 5, fine = 200, color = 'green', description = 'Acte de ne pas présenter une pièce d\'identité lorsque cela est légalement requis'},
        [15] = {title = 'Vigilantisme', class = 'Crime', id = 'P.C. 6015', months = 25, fine = 300, color = 'orange', description = 'Agir de son propre chef afin de faire respecter la loi ou se faire justice soi-même sans en avoir l\'autorité légale'},
        [16] = {title = 'Assemblée illégale', class = 'Délit', id = 'P.C. 6016', months = 0, fine = 300, color = 'orange', description = 'Lorsqu\'un grand groupe se rassemble dans un endroit pour lequel une approbation préalable est requise'},
        [17] = {title = 'Corruption gouvernementale', class = 'Crime', id = 'P.C. 6017', months = 300, fine = 15000, color = 'red', description = 'Utiliser sa position politique et le pouvoir pour son propre bénéfice'},
        [18] = {title = 'Harcèlement criminel', class = 'Crime', id = 'P.C. 6018', months = 30, fine = 500, color = 'orange', description = 'Lorsqu\'une personne surveille une autre sans son consentement'},
        [19] = {title = 'Complicité', class = 'Délit', id = 'P.C. 6019', months = 20, fine = 250, color = 'orange', description = 'Aider quelqu\'un à commettre ou encourager quelqu\'un à commettre un crime'},
        [20] = {title = 'Hébergement d\'un fugitif', class = 'Délit', id = 'P.C. 6020', months = 25, fine = 400, color = 'green', description = 'Lorsqu\'une personne cache volontairement une autre personne recherchée par les autorités'},
    },
    [7] = {
        [1] = {title = 'Possession simple de stupéfiants de classe A (drogues récréatives)', class = 'Délit', id = 'P.C. 7001', months = 10, fine = 150, color = 'green', description = 'Possession de stupéfiants de classe A inférieure à 14 grammes'},
        [2] = {title = 'Possession criminelle de stupéfiants de classe A (drogues récréatives)', class = 'Crime', id = 'P.C. 7002', months = 15, fine = 300, color = 'red', description = 'Possession criminelle de stupéfiants de classe A supérieure ou égale à 14 grammes'},
        [3] = {title = 'Cultivation simple de Marijuana', class = 'Délit', id = 'P.C. 7003', months = 20, fine = 500, color = 'green', description = 'Possession et/ou cultivation de marijuana (moins de 5 plants)'},
        [4] = {title = 'Cultivation criminelle de Marijuana', class = 'Crime', id = 'P.C. 7004', months = 60, fine = 1000, color = 'orange', description = 'Possession et/ou cultivation de marijuana (5 plants et plus)'},
        [5] = {title = 'Possession criminelle de stupéfiants de classe A (drogues récréatives) dans le but de revendre', class = 'Crime', id = 'P.C. 7005', months = 30, fine = 1000, color = 'orange', description = 'Possession criminelle de stupéfiants de classe A en quantité supérieure ou égale à 28 grammes et/ou dans un format facilitant la revente'},
        [6] = {title = 'Possession simple de stupéfiants de classe B (drogues synthétiques)', class = 'Délit', id = 'P.C. 7006', months = 15, fine = 300, color = 'green', description = 'Possession de stupéfiants de classe B inférieure à 7 grammes'},
        [7] = {title = 'Possession criminelle de stupéfiants de classe B (drogues synthétiques)', class = 'Crime', id = 'P.C. 7007', months = 20, fine = 500, color = 'red', description = 'Possession criminelle de stupéfiants de classe B supérieure ou égale à 7 grammes'},
        [8] = {title = 'Possession criminelle de stupéfiants de classe B (drogues synthétiques) dans le but de revendre', class = 'Crime', id = 'P.C. 7008', months = 35, fine = 1200, color = 'orange', description = 'Possession criminelle de stupéfiants de classe B en quantité supérieure ou égale à 28 grammes et/ou dans un format facilitant la revente'},
        [9] = {title = 'Possession simple de stupéfiants de classe C (drogues pharmaceutiques)', class = 'Délit', id = 'P.C. 7009', months = 20, fine = 500, color = 'green', description = 'Possession sans prescription de stupéfiants de classe C inférieure à 4 cachets ou une bouteille'},
        [10] = {title = 'Possession criminelle de stupéfiants de classe C (drogues pharmaceutiques)', class = 'Crime', id = 'P.C. 7010', months = 25, fine = 750, color = 'red', description = 'Possession sans prescription et criminelle de stupéfiants de classe C supérieure ou égale à 5 cachets ou 2 bouteilles'},
        [11] = {title = 'Possession criminelle de stupéfiants de classe C (drogues pharmaceutiques) dans le but de revendre', class = 'Crime', id = 'P.C. 7011', months = 40, fine = 1500, color = 'orange', description = 'Possession sans prescription et criminelle de stupéfiants de classe C en quantité supérieure ou égale à 10 cachets, 5 bouteilles et/ou dans un format facilitant la revente'},
        --[[[12] = {title = 'Délit Possession of Oxy / Vicodin', class = 'Délit', id = 'P.C. 7012', months = 7, fine = 500, color = 'green', description = 'The possession of oxy / vicodin in a small quantity usually for personal use without prescription'},
        [13] = {title = 'Crime manufacturing Possession of Oxy / Vicodin', class = 'Crime', id = 'P.C. 7013', months = 25, fine = 1500, color = 'red', description = 'The possession of a quantity of oxy / vicodin that is from manufacturing'},
        [14] = {title = 'Crime Possession of Oxy / Vicodin with Intent to Distribute', class = 'Crime', id = 'P.C. 7014', months = 35, fine = 4500, color = 'orange', description = 'The possession of a quantity of oxy / vicodin for distribution'},
        [15] = {title = 'Délit Possession of Ecstasy', class = 'Délit', id = 'P.C. 7015', months = 7, fine = 500, color = 'green', description = 'The possession of ecstasy in a small quantity usually for personal use'},
        [16] = {title = 'Crime manufacturing Possession of Ecstasy', class = 'Crime', id = 'P.C. 7016', months = 25, fine = 1500, color = 'red', description = 'The possession of a quantity of ecstasy that is from manufacturing'},
        [17] = {title = 'Possession of Ecstasy with Intent to Distribute', class = 'Crime', id = 'P.C. 7017', months = 35, fine = 4500, color = 'orange', description = 'The possession of a quantity of ecstasy for distribution'},
        [18] = {title = 'Délit Possession of Opium', class = 'Délit', id = 'P.C. 7018', months = 7, fine = 500, color = 'green', description = 'The possession of opium in a small quantity usually for personal use'},
        [19] = {title = 'Crime manufacturing Possession of Opium', class = 'Crime', id = 'P.C. 7019', months = 25, fine = 1500, color = 'red', description = 'The possession of a quantity of opium that is from manufacturing'},
        [20] = {title = 'Possession of Opium with Intent to Distribute', class = 'Crime', id = 'P.C. 7020', months = 35, fine = 4500, color = 'orange', description = 'The possession of a quantity of Opium for distribution'},
        [21] = {title = 'Délit Possession of Adderall', class = 'Délit', id = 'P.C. 7021', months = 7, fine = 500, color = 'green', description = 'The possession of adderall in a small quantity usually for personal use without prescription'},
        [22] = {title = 'Crime manufacturing Possession of Adderall', class = 'Crime', id = 'P.C. 7022', months = 25, fine = 1500, color = 'red', description = 'The possession of a quantity of adderall that is from manufacturing'},
        [23] = {title = 'Possession of Adderall with Intent to Distribute', class = 'Crime', id = 'P.C. 7023', months = 35, fine = 4500, color = 'orange', description = 'The possession of a quantity of Adderall for distribution'},
        [24] = {title = 'Délit Possession of Xanax', class = 'Délit', id = 'P.C. 7024', months = 7, fine = 500, color = 'green', description = 'The possession of xanax in a small quantity usually for personal use without prescription'},
        [25] = {title = 'Crime manufacturing Possession of Xanax', class = 'Crime', id = 'P.C. 7025', months = 25, fine = 1500, color = 'red', description = 'The possession of a quantity of xanax that is from manufacturing'},
        [26] = {title = 'Possession of Xanax with Intent to Distribute', class = 'Crime', id = 'P.C. 7026', months = 35, fine = 4500, color = 'orange', description = 'The possession of a quantity of Xanax for distribution'},
        [27] = {title = 'Délit Possession of Shrooms', class = 'Délit', id = 'P.C. 7027', months = 7, fine = 500, color = 'green', description = 'The possession of shrooms in a small quantity usually for personal use'},
        [28] = {title = 'Crime manufacturing Possession of Shrooms', class = 'Crime', id = 'P.C. 7028', months = 25, fine = 1500, color = 'red', description = 'The possession of a quantity of shrooms that is from manufacturing'},
        [29] = {title = 'Possession of Shrooms with Intent to Distribute', class = 'Crime', id = 'P.C. 7029', months = 35, fine = 4500, color = 'orange', description = 'The possession of a quantity of Shrooms for distribution'},
        [30] = {title = 'Délit Possession of Lean', class = 'Délit', id = 'P.C. 7030', months = 7, fine = 500, color = 'green', description = 'The possession of lean in a small quantity usually for personal use'},
        [31] = {title = 'Crime manufacturing Possession of Lean', class = 'Crime', id = 'P.C. 7031', months = 25, fine = 1500, color = 'red', description = 'The possession of a quantity of lean that is from manufacturing'},
        [32] = {title = 'Possession of Lean with Intent to Distribute', class = 'Crime', id = 'P.C. 7032', months = 35, fine = 4500, color = 'orange', description = 'The possession of a quantity of lean for distribution'},]]--
        [12] = {title = 'Vente de substance contrôlée', class = 'Délit', id = 'P.C. 7033', months = 20, fine = 600, color = 'green', description = 'Revente de toute substance contrôlée par la loi'},
        [13] = {title = 'Trafic de stupéfiants', class = 'Crime', id = 'P.C. 7034', months = 120, fine = 3000, color = 'red', description = 'Revente à grande échelle de toute substance contrôlée par la loi'},
        [14] = {title = 'Profanation de cadavre humain', class = 'Crime', id = 'P.C. 7035', months = 200, fine = 15000, color = 'orange', description = 'Détruire, déranger ou souiller délibérément un cadavre'},
        [15] = {title = 'Intoxication publique', class = 'Infraction', id = 'P.C. 7036', months = 0, fine = 75, color = 'green', description = 'Être intoxiqué en public'},
        [16] = {title = 'Grossière indécence', class = 'Délit', id = 'P.C. 7037', months = 0, fine = 150, color = 'green', description = 'S\'exposer de manière indécente en public'},
    },
    [8] = {
        [1] = {title = 'Possession criminelle d\'arme à feu de classe 1 (pistolets, armes de chasse)', class = 'Crime', id = 'P.C. 8001', months = 10, fine = 500, color = 'green', description = 'Possession d\'une arme à feu de classe 1 sans détenir et/ou avoir sur sa personne un permis valide et/ou n\'étant pas enregistrée correctement et/ou au nom de la personne l\'ayant en sa possession'},
        [2] = {title = 'Possession criminelle d\'arme à feu de classe 2 (fusils à pompe)', class = 'Crime', id = 'P.C. 8002', months = 15, fine = 750, color = 'green', description = 'Possession d\'une arme à feu de classe 2'},
        [3] = {title = 'Possession criminelle d\'arme à feu de classe 3 (pistolets mitrailleurs, fusils automatiques petit calibre)', class = 'Crime', id = 'P.C. 8003', months = 20, fine = 1000, color = 'green', description = 'Possession d\'une arme à feu de classe 3'},
        [4] = {title = 'Possession criminelle d\'arme à feu de classe 4 (armes automatiques ou semi-automatiques de gros calibre (fusils d\'assaut))', class = 'Crime', id = 'P.C. 8004', months = 25, fine = 1250, color = 'green', description = 'Possession d\'une arme à feu de classe 4'},
        [5] = {title = 'Revente criminelle d\'arme à feu de classe 1,2,3 ou 4', class = 'Crime', id = 'P.C. 8005', months = 50, fine = 1500, color = 'orange', description = 'Revente d\'une arme à feu de classe 1 sans en avoir l\'autorisation légale'},
        --[[[6] = {title = 'Revente criminelle d\'arme à feu de classe 2', class = 'Crime', id = 'P.C. 8006', months = 20, fine = 2000, color = 'orange', description = 'Revente d\'une arme à feu de classe 2 sans en avoir l\'autorisation légale'},
        [7] = {title = 'Revente criminelle d\'arme à feu de classe 3', class = 'Crime', id = 'P.C. 8007', months = 35, fine = 7000, color = 'orange', description = 'Revente d\'une arme à feu de classe 3 sans en avoir l\'autorisation légale'},
        [8] = {title = 'Revente criminelle d\'arme à feu de classe 4', class = 'Crime', id = 'P.C. 8008', months = 30, fine = 3000, color = 'orange', description = 'Revente d\'une arme à feu de classe 4 sans en avoir l\'autorisation légale'},]]--
        [6] = {title = 'Utilisation criminelle d\'une arme', class = 'Délit', id = 'P.C. 8009', months = 10, fine = 350, color = 'orange', description = 'Tout usage d\'une arme lors de la commission d\'un crime'},
        [7] = {title = 'Possession illégale de modifications d\'arme à feu', class = 'Délit', id = 'P.C. 8010', months = 10, fine = 300, color = 'green', description = 'Avoir en sa possession tout objet illégal de modification d\'armes à feu'},
        [8] = {title = 'Traffic d\'armes', class = 'Crime', id = 'P.C. 8011', months = 100, fine = 5000, color = 'red', description = 'Transporter ou avoir sur soi une quantité exagérée d\'armes à feu'},
        [9] = {title = 'Port d\'une arme de manière menaçante', class = 'Délit', id = 'P.C. 8012', months = 10, fine = 500, color = 'orange', description = 'Brandir ou montrer en public son arme inutilement'},
        [10] = {title = 'Insurrection', class = 'Crime', id = 'P.C. 8013', months = 120, fine = 15000, color = 'red', description = 'Tenter de renverser le gouvernement par la violence'},
        [11] = {title = 'Vol dans un espace aérien restreint', class = 'Crime', id = 'P.C. 8014', months = 15, fine = 1000, color = 'green', description = 'Piloter un aéronef dans un espace aérien contrôlé par le gouvernement'},
        [12] = {title = 'Traversée de la chaussée hors des passages désignés', class = 'Infraction', id = 'P.C. 8015', months = 0, fine = 75, color = 'green', description = 'Traverser une chaussée de manière dangereuse pour les véhicules à moteur'},
        [13] = {title = 'Usage criminel de matières explosives', class = 'Crime', id = 'P.C. 8016', months = 20, fine = 300, color = 'orange', description = 'Utilisation d\'explosifs pour commettre un crime'},
    },
    [9] = {
        [1] = {title = 'Conduite avec facultés affaiblies', class = 'Délit', id = 'P.C. 9001', months = 0, fine = 150, color = 'green', description = 'Conduire un véhicule à moteur en étant sous l\'influence de l\'alcool'},
        [2] = {title = 'Délit de fuite', class = 'Délit', id = 'P.C. 9002', months = 10, fine = 300, color = 'green', description = 'Se cacher ou fuir lors d\'une détention légale'},
        [3] = {title = 'Délit de fuite avec circonstances aggravantes', class = 'Crime', id = 'P.C. 9003', months = 15, fine = 600, color = 'orange', description = 'Ignorer délibérément la sécurité et se cacher ou fuir lors d\'une détention légale '},
        [4] = {title = 'Refus de céder le passage à un véhicule d\'urgence', class = 'Infraction', id = 'P.C. 9004', months = 0, fine = 500, color = 'green', description = 'Ne pas céder le passage aux véhicules d\'urgence'},
        [5] = {title = 'Non-respect d\'un dispositif de régulation du trafic', class = 'Infraction', id = 'P.C. 9005', months = 0, fine = 100, color = 'green', description = 'Ne pas suivre les dispositifs de sécurité de la chaussée'},
        [6] = {title = 'Véhicule non-conforme', class = 'Infraction', id = 'P.C. 9006', months = 0, fine = 75, color = 'green', description = 'Avoir un véhicule qui n\'est plus en état de fonctionnement et/ou non-conforme sur la chaussée'},
        [7] = {title = 'Conduite dangereuse 2ème degré', class = 'Infraction', id = 'P.C. 9007', months = 10, fine = 300, color = 'green', description = 'Conduire de manière à ne pas prendre consciemment en compte la sécurité et causant ou pouvant causer des dommages matériels'},
        [8] = {title = 'Conduite dangereuse 1er degré', class = 'Délit', id = 'P.C. 9008', months = 20, fine = 600, color = 'orange', description = 'Conduire de manière à ne pas prendre consciemment en compte la sécurité causant ou pouvant causer des dommages à autrui'},
        [9] = {title = 'Excès de vitesse au 3ème degré', class = 'Infraction', id = 'P.C. 9009', months = 0, fine = 100, color = 'green', description = 'Rouler jusqu\'à 19km/h au-dessus de la limite permise'},
        [10] = {title = 'Excès de vitesse au 2ème degré', class = 'Infraction', id = 'P.C. 9010', months = 0, fine = 200, color = 'green', description = 'Rouler jusqu\'à 39km/h au-dessus de la limite permise'},
        [11] = {title = 'Excès de vitesse au 1er degré', class = 'Infraction', id = 'P.C. 9011', months = 0, fine = 300, color = 'green', description = 'Rouler à 40km/h ou plus au-dessus de la limite permise'},
        [12] = {title = 'Conduite illégale d\'un véhicule', class = 'Infraction', id = 'P.C. 9012', months = 0, fine = 75, color = 'green', description = 'Conduite d\'un véhicule à moteur sans avoir sur soi et/ou détenir une licence appropriée'},
        [13] = {title = 'Demi-tour illégal', class = 'Infraction', id = 'P.C. 9013', months = 0, fine = 75, color = 'green', description = 'Faire un demi-tour dans un endroit interdit'},
        [14] = {title = 'Dépassement illégal', class = 'Infraction', id = 'P.C. 9014', months = 0, fine = 100, color = 'green', description = 'Procéder à un dépassement dangereux ou illégal'},
        [15] = {title = 'Conduite à contresens', class = 'Infraction', id = 'P.C. 9015', months = 0, fine = 125, color = 'green', description = 'Conduire dans la voie opposée'},
        [16] = {title = 'Virage illégal', class = 'Infraction', id = 'P.C. 9016', months = 0, fine = 75, color = 'green', description = 'Effectuer un virage à une intersection ou à un endroit où il n\'est pas permis de tourner'},
        [17] = {title = 'Non-respect d\'un panneau d\'arrêt', class = 'Infraction', id = 'P.C. 9017', months = 0, fine = 75, color = 'green', description = 'Omettre de s\'arrêter à un arrêt stop'},
        [18] = {title = 'Stationnement gênant ou illégal', class = 'Infraction', id = 'P.C. 9018', months = 0, fine = 75, color = 'green', description = 'Être stationné de façon gênante et/ou dans une zone où le stationnement est interdit'},
        [19] = {title = 'Fuite après accident', class = 'Délit', id = 'P.C. 9019', months = 20, fine = 400, color = 'green', description = 'Quitter les lieux d\'un accident impliquant un autre civil sans en avoir reçu l\'autorisation des autorités'},
        [20] = {title = 'Conduite sans phares et/ou clignotants', class = 'Infraction', id = 'P.C. 9020', months = 0, fine = 300, color = 'green', description = 'Conduire un véhicule ayant les phares hors d\'usage ou éteints'},
        [21] = {title = 'Course de rue', class = 'Crime', id = 'P.C. 9021', months = 5, fine = 350, color = 'green', description = 'Conduite d\'un véhicule lors d\'une compétition'},
        [22] = {title = 'Pilotage illégal d\'un aéronef', class = 'Crime', id = 'P.C. 9022', months = 10, fine = 1000, color = 'orange', description = 'Le fait de ne pas être en possession d\'une licence valide lors de l\'exploitation d\'un aéronef'},
        [23] = {title = 'Utilisation illégale d\'une voiture', class = 'Délit', id = 'P.C. 9023', months = 5, fine = 500, color = 'green', description = 'Conduire une voiture de quelqu\'un d\'autre sans son consentement'},
    },
    [10] = {
        [1] = {title = 'Chasse/pêche en zone interdite', class = 'Infraction', id = 'P.C. 10001', months = 0, fine = 500, color = 'green', description = 'La récolte de gibier et/ou de poisson dans des zones où l\'activité est interdite'},
        [2] = {title = 'Chasse/pêche sans permis', class = 'Infraction', id = 'P.C. 10002', months = 0, fine = 300, color = 'green', description = 'La récolte de gibier et/ou de poisson sans détenir et/ou avoir sur soi les autorisations légales nécéssaires'},
        [3] = {title = 'Cruauté animale', class = 'Délit', id = 'P.C. 10003', months = 40, fine = 1000, color = 'green', description = 'Agir cruellement envers un animal, délibérément ou pas'},
        [4] = {title = 'Chasse avec une arme inappropriée', class = 'Délit', id = 'P.C. 10004', months = 0, fine = 500, color = 'green', description = 'Utiliser une arme qui n\'est pas légalement déclarée ou fabriquée pour être utilisée pour la chasse'},
        --[5] = {title = 'Hunting outside of hunting hours', class = 'Infraction', id = 'P.C. 10005', months = 0, fine = 750, color = 'green', description = 'Harvesting animals outside of specified time to do so'},
        [5] = {title = 'Surpêche/Surchasse', class = 'Délit', id = 'P.C. 10006', months = 20, fine = 400, color = 'green', description = 'Prendre plus que la quantité légalement spécifiée de gibier et/ou de poisson'},
        [6] = {title = 'Braconnage', class = 'Crime', id = 'P.C. 10007', months = 30, fine = 750, color = 'red', description = 'Chasser/pêcher un animal qui est répertorié comme non prélevable légalement'},
    }
}

Config.AllowedJobs = {}
for index, value in pairs(Config.PoliceJobs) do
    Config.AllowedJobs[index] = value
end
for index, value in pairs(Config.AmbulanceJobs) do
    Config.AllowedJobs[index] = value
end
for index, value in pairs(Config.DojJobs) do
    Config.AllowedJobs[index] = value
end

Config.ColorNames = {
    [0] = "Metallic Black",
    [1] = "Metallic Graphite Black",
    [2] = "Metallic Black Steel",
    [3] = "Metallic Dark Silver",
    [4] = "Metallic Silver",
    [5] = "Metallic Blue Silver",
    [6] = "Metallic Steel Gray",
    [7] = "Metallic Shadow Silver",
    [8] = "Metallic Stone Silver",
    [9] = "Metallic Midnight Silver",
    [10] = "Metallic Gun Metal",
    [11] = "Metallic Anthracite Grey",
    [12] = "Matte Black",
    [13] = "Matte Gray",
    [14] = "Matte Light Grey",
    [15] = "Util Black",
    [16] = "Util Black Poly",
    [17] = "Util Dark silver",
    [18] = "Util Silver",
    [19] = "Util Gun Metal",
    [20] = "Util Shadow Silver",
    [21] = "Worn Black",
    [22] = "Worn Graphite",
    [23] = "Worn Silver Grey",
    [24] = "Worn Silver",
    [25] = "Worn Blue Silver",
    [26] = "Worn Shadow Silver",
    [27] = "Metallic Red",
    [28] = "Metallic Torino Red",
    [29] = "Metallic Formula Red",
    [30] = "Metallic Blaze Red",
    [31] = "Metallic Graceful Red",
    [32] = "Metallic Garnet Red",
    [33] = "Metallic Desert Red",
    [34] = "Metallic Cabernet Red",
    [35] = "Metallic Candy Red",
    [36] = "Metallic Sunrise Orange",
    [37] = "Metallic Classic Gold",
    [38] = "Metallic Orange",
    [39] = "Matte Red",
    [40] = "Matte Dark Red",
    [41] = "Matte Orange",
    [42] = "Matte Yellow",
    [43] = "Util Red",
    [44] = "Util Bright Red",
    [45] = "Util Garnet Red",
    [46] = "Worn Red",
    [47] = "Worn Golden Red",
    [48] = "Worn Dark Red",
    [49] = "Metallic Dark Green",
    [50] = "Metallic Racing Green",
    [51] = "Metallic Sea Green",
    [52] = "Metallic Olive Green",
    [53] = "Metallic Green",
    [54] = "Metallic Gasoline Blue Green",
    [55] = "Matte Lime Green",
    [56] = "Util Dark Green",
    [57] = "Util Green",
    [58] = "Worn Dark Green",
    [59] = "Worn Green",
    [60] = "Worn Sea Wash",
    [61] = "Metallic Midnight Blue",
    [62] = "Metallic Dark Blue",
    [63] = "Metallic Saxony Blue",
    [64] = "Metallic Blue",
    [65] = "Metallic Mariner Blue",
    [66] = "Metallic Harbor Blue",
    [67] = "Metallic Diamond Blue",
    [68] = "Metallic Surf Blue",
    [69] = "Metallic Nautical Blue",
    [70] = "Metallic Bright Blue",
    [71] = "Metallic Purple Blue",
    [72] = "Metallic Spinnaker Blue",
    [73] = "Metallic Ultra Blue",
    [74] = "Metallic Bright Blue",
    [75] = "Util Dark Blue",
    [76] = "Util Midnight Blue",
    [77] = "Util Blue",
    [78] = "Util Sea Foam Blue",
    [79] = "Uil Lightning blue",
    [80] = "Util Maui Blue Poly",
    [81] = "Util Bright Blue",
    [82] = "Matte Dark Blue",
    [83] = "Matte Blue",
    [84] = "Matte Midnight Blue",
    [85] = "Worn Dark blue",
    [86] = "Worn Blue",
    [87] = "Worn Light blue",
    [88] = "Metallic Taxi Yellow",
    [89] = "Metallic Race Yellow",
    [90] = "Metallic Bronze",
    [91] = "Metallic Yellow Bird",
    [92] = "Metallic Lime",
    [93] = "Metallic Champagne",
    [94] = "Metallic Pueblo Beige",
    [95] = "Metallic Dark Ivory",
    [96] = "Metallic Choco Brown",
    [97] = "Metallic Golden Brown",
    [98] = "Metallic Light Brown",
    [99] = "Metallic Straw Beige",
    [100] = "Metallic Moss Brown",
    [101] = "Metallic Biston Brown",
    [102] = "Metallic Beechwood",
    [103] = "Metallic Dark Beechwood",
    [104] = "Metallic Choco Orange",
    [105] = "Metallic Beach Sand",
    [106] = "Metallic Sun Bleeched Sand",
    [107] = "Metallic Cream",
    [108] = "Util Brown",
    [109] = "Util Medium Brown",
    [110] = "Util Light Brown",
    [111] = "Metallic White",
    [112] = "Metallic Frost White",
    [113] = "Worn Honey Beige",
    [114] = "Worn Brown",
    [115] = "Worn Dark Brown",
    [116] = "Worn straw beige",
    [117] = "Brushed Steel",
    [118] = "Brushed Black steel",
    [119] = "Brushed Aluminium",
    [120] = "Chrome",
    [121] = "Worn Off White",
    [122] = "Util Off White",
    [123] = "Worn Orange",
    [124] = "Worn Light Orange",
    [125] = "Metallic Securicor Green",
    [126] = "Worn Taxi Yellow",
    [127] = "police car blue",
    [128] = "Matte Green",
    [129] = "Matte Brown",
    [130] = "Worn Orange",
    [131] = "Matte White",
    [132] = "Worn White",
    [133] = "Worn Olive Army Green",
    [134] = "Pure White",
    [135] = "Hot Pink",
    [136] = "Salmon pink",
    [137] = "Metallic Vermillion Pink",
    [138] = "Orange",
    [139] = "Green",
    [140] = "Blue",
    [141] = "Mettalic Black Blue",
    [142] = "Metallic Black Purple",
    [143] = "Metallic Black Red",
    [144] = "Hunter Green",
    [145] = "Metallic Purple",
    [146] = "Metaillic V Dark Blue",
    [147] = "MODSHOP BLACK1",
    [148] = "Matte Purple",
    [149] = "Matte Dark Purple",
    [150] = "Metallic Lava Red",
    [151] = "Matte Forest Green",
    [152] = "Matte Olive Drab",
    [153] = "Matte Desert Brown",
    [154] = "Matte Desert Tan",
    [155] = "Matte Foilage Green",
    [156] = "DEFAULT ALLOY COLOR",
    [157] = "Epsilon Blue",
    [158] = "Unknown",
}

Config.ColorInformation = {
    [0] = "black",
    [1] = "black",
    [2] = "black",
    [3] = "darksilver",
    [4] = "silver",
    [5] = "bluesilver",
    [6] = "silver",
    [7] = "darksilver",
    [8] = "silver",
    [9] = "bluesilver",
    [10] = "darksilver",
    [11] = "darksilver",
    [12] = "matteblack",
    [13] = "gray",
    [14] = "lightgray",
    [15] = "black",
    [16] = "black",
    [17] = "darksilver",
    [18] = "silver",
    [19] = "utilgunmetal",
    [20] = "silver",
    [21] = "black",
    [22] = "black",
    [23] = "darksilver",
    [24] = "silver",
    [25] = "bluesilver",
    [26] = "darksilver",
    [27] = "red",
    [28] = "torinored",
    [29] = "formulared",
    [30] = "blazered",
    [31] = "gracefulred",
    [32] = "garnetred",
    [33] = "desertred",
    [34] = "cabernetred",
    [35] = "candyred",
    [36] = "orange",
    [37] = "gold",
    [38] = "orange",
    [39] = "red",
    [40] = "mattedarkred",
    [41] = "orange",
    [42] = "matteyellow",
    [43] = "red",
    [44] = "brightred",
    [45] = "garnetred",
    [46] = "red",
    [47] = "red",
    [48] = "darkred",
    [49] = "darkgreen",
    [50] = "racingreen",
    [51] = "seagreen",
    [52] = "olivegreen",
    [53] = "green",
    [54] = "gasolinebluegreen",
    [55] = "mattelimegreen",
    [56] = "darkgreen",
    [57] = "green",
    [58] = "darkgreen",
    [59] = "green",
    [60] = "seawash",
    [61] = "midnightblue",
    [62] = "darkblue",
    [63] = "saxonyblue",
    [64] = "blue",
    [65] = "blue",
    [66] = "blue",
    [67] = "diamondblue",
    [68] = "blue",
    [69] = "blue",
    [70] = "brightblue",
    [71] = "purpleblue",
    [72] = "blue",
    [73] = "ultrablue",
    [74] = "brightblue",
    [75] = "darkblue",
    [76] = "midnightblue",
    [77] = "blue",
    [78] = "blue",
    [79] = "lightningblue",
    [80] = "blue",
    [81] = "brightblue",
    [82] = "mattedarkblue",
    [83] = "matteblue",
    [84] = "matteblue",
    [85] = "darkblue",
    [86] = "blue",
    [87] = "lightningblue",
    [88] = "yellow",
    [89] = "yellow",
    [90] = "bronze",
    [91] = "yellow",
    [92] = "lime",
    [93] = "champagne",
    [94] = "beige",
    [95] = "darkivory",
    [96] = "brown",
    [97] = "brown",
    [98] = "lightbrown",
    [99] = "beige",
    [100] = "brown",
    [101] = "brown",
    [102] = "beechwood",
    [103] = "beechwood",
    [104] = "chocoorange",
    [105] = "yellow",
    [106] = "yellow",
    [107] = "cream",
    [108] = "brown",
    [109] = "brown",
    [110] = "brown",
    [111] = "white",
    [112] = "white",
    [113] = "beige",
    [114] = "brown",
    [115] = "brown",
    [116] = "beige",
    [117] = "steel",
    [118] = "blacksteel",
    [119] = "aluminium",
    [120] = "chrome",
    [121] = "wornwhite",
    [122] = "offwhite",
    [123] = "orange",
    [124] = "lightorange",
    [125] = "green",
    [126] = "yellow",
    [127] = "blue",
    [128] = "green",
    [129] = "brown",
    [130] = "orange",
    [131] = "white",
    [132] = "white",
    [133] = "darkgreen",
    [134] = "white",
    [135] = "pink",
    [136] = "pink",
    [137] = "pink",
    [138] = "orange",
    [139] = "green",
    [140] = "blue",
    [141] = "blackblue",
    [142] = "blackpurple",
    [143] = "blackred",
    [144] = "darkgreen",
    [145] = "purple",
    [146] = "darkblue",
    [147] = "black",
    [148] = "purple",
    [149] = "darkpurple",
    [150] = "red",
    [151] = "darkgreen",
    [152] = "olivedrab",
    [153] = "brown",
    [154] = "tan",
    [155] = "green",
    [156] = "silver",
    [157] = "blue",
    [158] = "black",
}

Config.ClassList = {
    [0] = "Compact",
    [1] = "Sedan",
    [2] = "SUV",
    [3] = "Coupe",
    [4] = "Muscle",
    [5] = "Sport Classic",
    [6] = "Sport",
    [7] = "Super",
    [8] = "Motorbike",
    [9] = "Off-Road",
    [10] = "Industrial",
    [11] = "Utility",
    [12] = "Van",
    [13] = "Bike",
    [14] = "Boat",
    [15] = "Helicopter",
    [16] = "Plane",
    [17] = "Service",
    [18] = "Emergency",
    [19] = "Military",
    [20] = "Commercial",
    [21] = "Train"
}

function GetJobType(job)
	if Config.PoliceJobs[job] then
		return 'police'
	elseif Config.AmbulanceJobs[job] then
		return 'ambulance'
	elseif Config.DojJobs[job] then
		return 'doj'
	else
		return nil
	end
end
